### ISSUE TITLE
Stuck at "Starting the development server"

### ISSUE THREAD

**Issue by mr-bjerre** [davidkpiano/frontend-masters-react-workshop#5]
I have a MacBook Pro on BigSur. I cloned the repo, `yarn install` and then `yarn start`. Then its stuck at 

    Starting the development server...

Any clue what the issue could be?

Yarn version is 1.22.10, npm is 6.14.10 (doesn't work with npm either), node is 14.15.4.

**Comment by mr-bjerre** [comment]
Turns out I just had to close Safari and Chrome and then try again. Odd...

**Comment by JaredPotter** [comment]
@mr-bjerre's solution also fixed this for me. I stopped the `start` process, closed all browsers, and then started and it connected correctly.
